#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApplication
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SiteDB")]
	public partial class DataClassesSiteVisitorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesSiteVisitorDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SiteDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSiteVisitorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSiteVisitorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSiteVisitorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSiteVisitorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CreatingFeedbackComment")]
		public int CreatingFeedbackComment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ViitorName", DbType="NVarChar(50)")] string viitorName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitorEmail", DbType="NVarChar(50)")] string visitorEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitorCommentTitle", DbType="Text")] string visitorCommentTitle, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitorComment", DbType="Text")] string visitorComment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitorImage", DbType="Image")] System.Data.Linq.Binary visitorImage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), viitorName, visitorEmail, visitorCommentTitle, visitorComment, visitorImage);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
