//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorsFeedBack
    {
        public int VisitorId { get; set; }
        public string VisitorName { get; set; }
        public string VisitorEmail { get; set; }
        public string VisitorCommentTitle { get; set; }
        public string VisitorComment { get; set; }
        public string FeedbackTime { get; set; }
        public byte[] VisitorImage { get; set; }
    }
}
